groups:
  - name: Blackbox_Exporter_rules
    rules:
      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})"
          description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: URLDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "URL [{{ $labels.instance }}] down"
          description: "URL [{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."

      - alert: Port(Service) Down
        expr: probe_success{job="Port Service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Port(Service) [{{ $labels.instance }}] down"
          description: "Port(Service) [{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."
