---
# tasks file for redis_exporter
- name: Adding the user for redis_exporter
  user:
    name: '{{ redis_exporter_user }}'
    shell: /bin/false
    create_home: no

- name: Download and extracted redis exporter
  unarchive:
    src: https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: True

- name: Copy redis exporter excutable file
  copy:
    src: '/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    remote_src: yes
    owner: '{{ redis_exporter_user }}'
    group: '{{ redis_exporter_user }}'
    mode: 0770
  with_items:
    - redis_exporter

- name: Copy redis exporter service file
  template:
    src: '{{ item }}'
    dest: /etc/systemd/system/redis_exporter.service
  with_items:
    - redis_exporter.service.j2

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start service redis_exporter, if not started
  service:
    name: redis_exporter
    state: started
    enabled: yes

- name: Delete download
  file:
    path: /tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64
    state: absent
